version: '3'

services:
    app:
        build: .docker/php
        container_name: dojo-php
        volumes:
            - .:/var/www
            - ./.docker/php/config:/usr/local/etc/php/conf.d/
        networks:
            - app-network
        links:
          - db

    nginx:
        build: .docker/nginx
        container_name: dojo-nginx
        restart: always
        tty: true
        ports:
            - "4444:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
